name: Deploy to Render

on:
    push:
        branches: [main]

permissions:
    contents: read
    deployments: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: Production

        steps:
            - uses: actions/checkout@v4

            - name: Trigger Render deploy
              run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

            - name: Create GitHub Deployment
              uses: chrnorm/deployment-action@v2
              id: deployment
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  environment: Production

            - name: Update Deployment Status
              uses: chrnorm/deployment-status@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  deployment-id: ${{ steps.deployment.outputs.deployment_id }}
                  state: success
                  environment-url: https://ngsa-exam-api.onrender.com/
